language: generic
sudo: required
services : 
  - docker

before_install:
  - docker build -t smukes/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true smukes/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-ap-south-1-269642219333"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  