language: generic
sudo: required
services : 
  - docker

before_install:
  - docker build -t smukes/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true smukes/docker-react npm run test